spring:
  data:
    mongodb:
      uri: mongodb+srv://sheeryndsouza2204_db_user:sheeshaa2207@cluster0.ud4xnhv.mongodb.net/lead_management?retryWrites=true&w=majority
  
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 4000

app:
  cors:
    allowed-origins: "http://localhost:4200"
